<?xml version="1.0"?>
<!-- Revolute-Revolute Manipulator -->
<robot name="car_ackermann" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Physical Constant Macros -->
  <xacro:property name="M_PI" value="3.1415926535897931" />
  <!-- Dimension Macros -->
  <xacro:property name="carLength" value="0.3" />
  <xacro:property name="carWidth" value="0.15" />
  <xacro:property name="carHeight" value="0.1" />
  <xacro:property name="wheelRadius" value="0.06" />
  <xacro:property name="wheelWidth" value="0.025" />
    
  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find car_ackermann_description)/urdf/car_ackermann.gazebo" />
  <!-- Import Rviz colors -->
  <xacro:include filename="$(find car_ackermann_description)/urdf/materials.xacro" />

  <!-- Main body -->
    <link name="base_link">
        <inertial>
            <mass value="0.2" />
            <origin xyz="0 0 0" /> 
            <inertia  ixx="0.2" ixy="0.0"  ixz="0.0"  iyy="0.2"  iyz="0.0"  izz="0.2" />
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${carLength} ${carWidth} ${carHeight}" />
            </geometry>
            <material name="Red"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${carLength} ${carWidth} ${carHeight}" />
            </geometry>
        </collision>
    </link>
    <gazebo reference="base_link">
        <material>Gazebo/Red</material>
    </gazebo>
    
    <!-- Front link of Ackermann -->
    <!-- Joins to the Car body -->
    <joint name="front_joint" type="fixed">
    	<parent link="base_link"/>
    	<child link="front_link"/>
    	<origin xyz="0.16 0.0 -0.1"/>
    </joint>
    <link name="front_link">
        <inertial>
            <mass value="0.01" />
            <origin xyz="0 0 0" /> 
            <inertia  ixx="0.01" ixy="0.0"  ixz="0.0"  iyy="0.01"  iyz="0.0"  izz="0.01" />
        </inertial>
        <visual>
            <geometry>
                <box size="${carLength*0.05} ${carWidth} ${carHeight*0.05}" />
            </geometry>
            <material name="Aqua"/>
        </visual>
        <collision>
            <geometry>
                <box size="${carLength*0.05} ${carWidth} ${carHeight*0.05}" />
            </geometry>
        </collision>
    </link>
    <gazebo reference="front_link">
        <material>Gazebo/Green</material>
    </gazebo>
    
    <!-- a link aligned with the steer direction -->
    <joint name="steer_joint" type="revolute" >
        <limit lower="-0.5" upper="0.5" effort="100" velocity="10" />
        <axis xyz="0 0 1" />
        <parent link="front_link" />
        <child link="steer_link" />
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
    </joint>
    <link name="steer_link">
        <inertial>
            <mass value="0.01" />
            <origin xyz="0 0 0" />
            <inertia  ixx="0.01" ixy="0.0"  ixz="0.0"  iyy="0.01"  iyz="0.0"  izz="0.01" />
        </inertial>
        <visual>
            <origin xyz="-0.02 0 0" />
            <geometry>
                <box size="${carLength*0.1} ${carWidth*0.133} ${carHeight*0.05}" />
            </geometry>
            <material name="Green"/>
        </visual>
        <collision>
            <origin xyz="0.02 0 0" />
            <geometry>
                <box size="${carLength*0.1} ${carWidth*0.133} ${carHeight*0.05}" />
            </geometry>
        </collision>
    </link>
    <gazebo reference="steer_link">
        <material>Gazebo/Green</material>
    </gazebo>

    <!-- the left Ackermann bar -->
    <joint name="front_left_bar_joint" type="revolute" >
        <limit lower="-0.5" upper="0.5" effort="100" velocity="10" />
        <axis xyz="0 0 1" />
        <parent link="front_link" />
        <child link="front_left_bar_link" />
        <origin xyz="0.0 0.06 0.0" rpy="0 0 0" />
    </joint>
    <link name="front_left_bar_link">
        <inertial>
            <mass value="0.01" />
            <origin xyz="0 0 0" />
            <inertia  ixx="0.01" ixy="0.0"  ixz="0.0"  iyy="0.01"  iyz="0.0"  izz="0.01" />
        </inertial>
        <visual>
            <origin xyz="-0.02 0 0" />
            <geometry>
                <box size="${carLength*0.1} ${carWidth*0.133} ${carHeight*0.05}" />
            </geometry>
            <material name="Green"/>
        </visual>
        <collision>
            <origin xyz="-0.02 0 0" />
            <geometry>
                <box size="${carLength*0.1} ${carWidth*0.133} ${carHeight*0.05}" />
            </geometry>
        </collision>
    </link>
    <gazebo reference="front_left_bar_link">
        <material>Gazebo/Green</material>
    </gazebo>

    <!-- the right Ackermann bar -->
    <joint name="front_right_bar_joint" type="revolute" >
        <limit lower="-0.5" upper="0.5" effort="100" velocity="10" />
        <axis xyz="0 0 1" />
        <parent link="front_link" />
        <child link="front_right_bar_link" />
        <origin xyz="0.0 -0.06 0.0" rpy="0 0 0" />
    </joint>
    
    <link name="front_right_bar_link">
        <inertial>
            <mass value="0.01" />
            <origin xyz="0 0 0" />
            <inertia  ixx="0.01" ixy="0.0"  ixz="0.0"  iyy="0.01"  iyz="0.0"  izz="0.01" />
        </inertial>
        <visual>
            <origin xyz="-0.02 0 0" />
            <geometry>
                <box size="${carLength*0.1} ${carWidth*0.133} ${carHeight*0.05}" />
            </geometry>
            <material name="Green"/>
        </visual>
        <collision>
            <origin xyz="-0.02 0 0" />
            <geometry>
                <box size="${carLength*0.1} ${carWidth*0.133} ${carHeight*0.05}" />
            </geometry>
        </collision>
    </link>
    <gazebo reference="front_right_bar_link">
        <material>Gazebo/Green</material>
    </gazebo>


	<!-- the front left wheel -->
    <joint name="front_left_wheel_joint" type="continuous" >
        <axis xyz="0 1 0" />
        <parent link="front_left_bar_link" />
        <child link="front_left_wheel_link" />
        <origin xyz="0 0.04 0" rpy="0 0 0" />
    </joint>
    <link name="front_left_wheel_link">
        <inertial>
            <mass value="0.01" />
            <origin xyz="0 0 0" /> 
            <inertia  ixx="0.01" ixy="0.0"  ixz="0.0"  iyy="0.01"  iyz="0.0"  izz="0.01" />
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
            <geometry>
                <cylinder radius="${wheelRadius}" length="${wheelWidth}" />
            </geometry>
            <material name="Green"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
            <geometry>
                <cylinder radius="${wheelRadius}" length="${wheelWidth}" />
            </geometry>
        </collision>
    </link>
    <gazebo reference="front_left_wheel_link">
        <material>Gazebo/Green</material>
    </gazebo>

	<!-- the front right wheel -->
    <joint name="front_right_wheel_joint" type="continuous" >
        <axis xyz="0 1 0" />
        <parent link="front_right_bar_link" />
        <child link="front_right_wheel_link" />
        <origin xyz="0 -0.04 0" rpy="0 0 0" />
    </joint>
    <link name="front_right_wheel_link">
        <inertial>
            <mass value="0.01" />
            <origin xyz="0 0 0" /> 
            <inertia  ixx="0.01" ixy="0.0"  ixz="0.0"  iyy="0.01"  iyz="0.0"  izz="0.01" />
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
            <geometry>
                <cylinder radius="${wheelRadius}" length="${wheelWidth}" />
            </geometry>
            <material name="Green"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
            <geometry>
                <cylinder radius="${wheelRadius}" length="${wheelWidth}" />
            </geometry>
        </collision>
    </link>
    <gazebo reference="front_right_wheel_link">
        <material>Gazebo/Green</material>
        <turnGravityOff>false</turnGravityOff>
    </gazebo>

  <!-- differential drive -->
<gazebo>
    <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
        <alwaysOn>true</alwaysOn>
        <updateRate>40</updateRate>
        <legacyMode>false</legacyMode>
        <leftJoint>back_left_wheel_joint</leftJoint>
        <rightJoint>back_right_wheel_joint</rightJoint>
        <wheelSeparation>0.35</wheelSeparation>
        <wheelDiameter>0.12</wheelDiameter>
        <torque>5</torque>
        <commandTopic>cmd_vel</commandTopic>
        <odometryTopic>odom</odometryTopic>
        <odometryFrame>odom</odometryFrame>
        <robotBaseFrame>base_link</robotBaseFrame>
        <publishWheelTF>false</publishWheelTF>
        <publishWheelJointState>false</publishWheelJointState>
        <rosDebugLevel>na</rosDebugLevel>
        <wheelAcceleration>0</wheelAcceleration>
        <wheelTorque>5</wheelTorque>
        <odometrySource>world</odometrySource>
        <publishTf>1</publishTf>
    </plugin>
</gazebo>

	<!-- the Ackerman bar -->

    <joint name="ackermann_joint_left" type="fixed" >
        
        
        <parent link="ackermann_bar_link" />
        <child link="front_left_bar_link" />
        <origin xyz="0 0.07 0" rpy="0 0 0" />
    </joint>
        <joint name="ackermann_joint_right" type="fixed" >
        
        
        <parent link="ackermann_bar_link" />
        <child link="front_right_bar_link" />
        <origin xyz="0 -0.07 0" rpy="0 0 0" />
    </joint>

    <joint name="ackermann_joint" type="revolute" >
        <limit lower="-0.5" upper="0.5" effort="100" velocity="10" />
        <axis xyz="0 0 1" />
        <parent link="steer_link" />
        <child link="ackermann_bar_link" />
        <origin xyz="-0.04 0 0" rpy="0 0 0" />
    </joint>

    <link name="ackermann_bar_link">
        <inertial>
            <mass value="0.01" />
            <origin xyz="0 0 0" /> 
            <inertia  ixx="0.01" ixy="0.0"  ixz="0.0"  iyy="0.01"  iyz="0.0"  izz="0.01" />
        </inertial>
        <visual>
            <geometry>
                <box size="${carLength*0.05} ${carWidth} ${carHeight*0.1}" />
            </geometry>
            <material name="Green"/>
        </visual>
        <collision>
            <geometry>
                <box size="${carLength*0.05} ${carWidth} ${carHeight*0.1}" />
            </geometry>
        </collision>
    </link>
    <gazebo reference="front_link">
        <material>Gazebo/Green</material>
    </gazebo>
    <gazebo reference="ackermann_bar_link">
        <material>Gazebo/Blue</material>
    </gazebo>


    
	<!-- the back left wheel -->
    <joint name="back_left_wheel_joint" type="continuous" >
        <axis xyz="0 1 0" />
        <parent link="base_link" />
        <child link="back_left_wheel_link" />
        <origin xyz="-0.16 0.1 -0.1" rpy="0 0 0" />
    </joint>
    <link name="back_left_wheel_link">
        <inertial>
            <mass value="0.01" />
            <origin xyz="0 0 0" /> 
            <inertia  ixx="0.01" ixy="0.0"  ixz="0.0"  iyy="0.01"  iyz="0.0"  izz="0.01" />
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
            <geometry>
                <cylinder radius="${wheelRadius}" length="${wheelWidth}" />
            </geometry>
            <material name="Black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
            <geometry>
                <cylinder radius="${wheelRadius}" length="${wheelWidth}" />
            </geometry>
        </collision>
    </link>
    <gazebo reference="back_left_wheel_link">
        <material>Gazebo/Black</material>
    </gazebo>
    
	<!-- the back right wheel -->
    <joint name="back_right_wheel_joint" type="continuous" >
        <axis xyz="0 1 0" />
        <parent link="base_link" />
        <child link="back_right_wheel_link" />
        <origin xyz="-0.16 -0.1 -0.1" rpy="0 0 0" />
    </joint>
    <link name="back_right_wheel_link">
        <inertial>
            <mass value="0.01" />
            <origin xyz="0 0 0" /> 
            <inertia  ixx="0.01" ixy="0.0"  ixz="0.0"  iyy="0.01"  iyz="0.0"  izz="0.01" />
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
            <geometry>
                <cylinder radius="${wheelRadius}" length="${wheelWidth}" />
            </geometry>
            <material name="Black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
            <geometry>
                <cylinder radius="${wheelRadius}" length="${wheelWidth}" />
            </geometry>
        </collision>
    </link>
    <gazebo reference="back_right_wheel_link">
        <material>Gazebo/Black</material>
    </gazebo>

  <joint name="hokuyo_joint" type="fixed">
    <origin  xyz="0 0 0.05" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="hokuyo_link"/>
  </joint>

  <!-- Hokuyo Laser -->
  <link name="hokuyo_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="0.1 0.1 0.1"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://car_ackermann_description/meshes/hokuyo.dae"/>
      </geometry>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>


  <transmission name="tran">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="steer_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>



</robot>
